import type { Metadata } from "next";
import localFont from "next/font/local";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Navbar } from "@/components/ui/navbar";
import CustomSidebar from "@/components/ui/custom-sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  //   <html lang="en">
  //     <body
       
  //     >
  //         <Navbar />

  //       <SidebarProvider>
  //         <AppSidebar />
  //         {children}
  //       </SidebarProvider>
  //     </body>
  //   </html>
  <html lang="en">
      <body>
        <CustomSidebar />
        <Navbar />
        <div className="ml-0 md:ml-64">{children}</div> {/* Adjust for sidebar */}
      </body>
    </html>
  );
}

